language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.8
  - 1.9
  - nightly

notifications:
  email: false

script:
  - julia --project -e 'using Pkg; Pkg.instantiate(); Pkg.build(); Pkg.test(coverage=true)'

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("juliaexample")); using Coverage; Codecov.submit(Codecov.process_folder())'
